// Messages store
export const GET_ALL_USER_MESSAGES = 'GET_ALL_USER_MESSAGES';
export const DELETE_MASSEGE = 'DELETE_MASSEGE';
export const CREATE_NEW_MSG = 'CREATE_NEW_MSG';
export const SET_CHOSEN_MSG = 'SET_CHOSEN_MSG';

// Navigation store
export const SET_CURRENT_TAB_IN_MANAGER = 'SET_CURRENT_TAB_IN_MANAGER';
export const SET_ERROR_TYPE_OF_EMAIL = 'SET_ERROR_TYPE_OF_EMAIL';
